{% set name = "multigifview" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b63cbea3572ba102e846aa498de0ff47ab864803674f2aad1feef4f8600c7a01

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - multigifview = multigifview:main
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools >=40
    - setuptools_scm_git_archive
  run:
    - python
    - qt.py >=1.2
    - pyqt >=5.12
    - importlib_metadata  # [py<38]
    # Not sure why sip is needed for windows. May be a bug with PyQt5.sip which is avoided by installing the independent sip package, but 'sip.delete' was missing only on Windows
    - sip  # [win]

test:
  commands:
    - multigifview -h

about:
  home: https://github.com/johnomotani/multigifview
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE
  summary: Simple gif viewer
  dev_url: https://github.com/johnomotani/multigifview

extra:
  recipe-maintainers:
    - johnomotani
