{% set name = "multigifview" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8f527728d9fda7cc342eec7b5973ee18f525e6f53d432a38fbde18b07b3b2cc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - multigifview = multigifview:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=40
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - qt.py >=1.2
    - pyqt >=5.12

test:
  requires:
    - python {{ python_min }}
  commands:
    - multigifview -h

about:
  home: https://github.com/johnomotani/multigifview
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE
  summary: Simple gif viewer
  dev_url: https://github.com/johnomotani/multigifview

extra:
  recipe-maintainers:
    - johnomotani
