{% set name = "multigifview" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e53376c9454721237a697f6322cad9a556959f4004fbfe34b8cae3a41f267a2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - multigifview = multigifview:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=40
    - setuptools_scm_git_archive
  run:
    - python >=3.8
    - qt.py >=1.2
    - pyqt >=5.12

test:
  commands:
    - multigifview -h

about:
  home: https://github.com/johnomotani/multigifview
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENCE
  summary: Simple gif viewer
  dev_url: https://github.com/johnomotani/multigifview

extra:
  recipe-maintainers:
    - johnomotani
